# Generated by Django 3.2.8 on 2023-09-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0002_disciplina_ch'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='sigla',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='ch',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
