# Generated by Django 3.2.8 on 2023-09-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0004_auto_20230919_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
