# Generated by Django 4.2.5 on 2023-10-12 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0006_comentario_dislikes_comentario_likes_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='liked',
            field=models.BooleanField(),
        ),
    ]
