# Generated by Django 4.2.5 on 2023-10-12 01:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('avaliacao', '0008_remove_comentario_dislikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='curtidas',
            field=models.ManyToManyField(blank=True, related_name='curtidas', to=settings.AUTH_USER_MODEL),
        ),
    ]
