# Generated by Django 4.2.5 on 2023-10-12 01:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('avaliacao', '0009_comentario_curtidas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='curtidas',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='likes',
        ),
        migrations.AddField(
            model_name='comentario',
            name='curtida',
            field=models.ManyToManyField(blank=True, related_name='comentarios_curtidos', to=settings.AUTH_USER_MODEL),
        ),
    ]
