# Generated by Django 4.2.5 on 2023-10-12 12:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0010_remove_comentario_curtidas_remove_comentario_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='avaliacao',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='avaliacao_media',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
