# Generated by Django 4.2.5 on 2023-11-27 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0011_comentario_avaliacao_disciplina_avaliacao_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='disciplina_images/'),
        ),
    ]
