# Generated by Django 4.2.5 on 2023-12-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0012_disciplina_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='static/img'),
        ),
    ]
